@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTIxODk4OGY4Y2I5YWJkZmVjMGZjNWIiLCJpYXQiOjE3ODEwMjc2NzgsImV4cCI6MTc4MTAzMTI3OH0.YjZMqZHEBgE-YHX2XDdV1YQ-gWJ4JgjnaWMT1tLsIcY 
### Login Request
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"testuser@gmail.com", 
    "password":"mypassword123"
}
### Create a new flood Report (Secured)
POST http://localhost:5000/api/reports
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "issueType": "blocked drainage",
    "description": "The main drainage layout along the road is completelyclogged with plastic waste causing heavy overflows.",
    "location": "Lokoja, Kogi State"
}

### Create a new flood Report (Secured)
POST http://localhost:5000/api/reports
Content-Type: application/json
Authorization: Bearer PASTE_YOUR_LONG_JWT_TOKEN_HERE

{
    "issueType": "flooding",
    "description": "The water level has broken past the sandbags near the residential layouts.",
    "location": "Ganaja, Lokoja"
}